### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by ImprovedTube**

### CODE REVIEW

**Comment by raszpl** [comment]
Afaik old project was on GPL 3, once something is GPL 3 it cant be changed into more restrictive license ergo its still gpl 3

**Comment by ImprovedTube** [comment]
hi :) 🤗 you might want to read / catch up here https://github.com/code-charity/youtube/pull/2421 and other @mentiones
>Isn't it wonderful (mentally & and for the users), to have a project where at least 2 people have thought about 100s or 1000s of issues?

RE: License:  The first line indicates copyrights. 
> ©️ 2012-2024   ( no warranty / liablity )     Thank you! 

 (Then why quote halves of sentences?)  
 > For simplicity & intellectual growth: Unless stated otherwise, ... And free of copyrights to the original maintainers. (these intellectual contributions are granted to the original maintainers free-of-charge, non-exclusively, for publishing & modification. Contributors do have the right to be mentioned in credits)

( _In other words: External pull requests are assumed to be under a viral free license considering the rest of the world (as it is a common standard), but also with a normal (non-viral) permission (only to the original maintainers)(, so that and the original project can simply run as always / as the first 9 years when few pull requests were merged.)_ )

- More interestingly, you might also read the draft for a new type of license acknowledging developers as shareholders (which they mentally are. Something that existing licenses are missing. Greetings @maniues)   
- While you were essential for the Project in 2024.

**Comment by ImprovedTube** [comment]
hi :) 🤗 you might want to read / catch up here https://github.com/code-charity/youtube/pull/2421 and other @mentiones
>Isn't it wonderful (mentally & and for the users), to have a project where at least 2 people have thought about 100s or 1000s of issues?

RE: License:  The first line indicates copyrights. 
> ©️ 2012-2024   ( no warranty / liablity )     Thank you! 

 (Then why quote halves of sentences?)  
 > For simplicity & intellectual growth: Unless stated otherwise, ... And free of copyrights to the original maintainers. (these intellectual contributions are granted to the original maintainers free-of-charge, non-exclusively, for publishing & modification. Contributors do have the right to be mentioned in credits)

( _In other words: External pull requests are assumed to be under a viral free license considering the rest of the world (as it is a common standard), but also with a normal (non-viral) permission (only to the original maintainers)(, so that and the original project can simply run as always / as the first 9 years when few pull requests were merged.)_ )

- More interestingly, you might also read the draft for a new type of license acknowledging developers as shareholders (which they mentally are. Something that existing licenses are missing. Greetings @maniues)   
- While you were essential for the Project in 2024 💕.

**Comment by ImprovedTube** [comment]
(As said) i have a lot of understanding for your exhaustion(?) 

i was utterly amazed and so relieved you were working a lot these month!  And regret i was unable unexpectedly to work here in June.

**Comment by ImprovedTube** [comment]
And i don't know why to keep up "competitive misunderstandings"?  - to belittle ourselves and our project?   

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  

You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be? 
Among other since we don't have a private conversation and we represent a popular app, i usually mean to apply the courtesy / professional-distance in public.

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a 2 confusing words, when quoting badly and we can speculatively assume Vivaldi misunderstood that - or i can just regret the lack of a public bug tracker.   I appreciate Vivaldi for productivity and i'm not sure what to think about it also being an emotional brand for "doing one's own thing frustratingly" ? (on [sidepanels](https://github.com/code-charity/youtube/discussions/2338#discussioncomment-9717479).  Sometimes i might  express the perspective of running an app over these years with special attention for the whole & details one never expected or wanted to care about, which can be mentally rewarding or painful. And i'm glad about your work as said!  



Hope you are fine!

**Comment by ImprovedTube** [comment]
And i don't know why to keep up "competitive misunderstandings"?  - to belittle ourselves and our project?   

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  

You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be?  i usually mean to apply the courtesy /professional-distance to comment rather positively and ignore confusing impulses  (among other since we represent a popular app in public. Feel free to use email to or any)

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a headline of some paragraph - when quoting badly isolated and we can speculatively assume Vivaldi misunderstood that - or i can just regret the lack of a public bug tracker.   I appreciated Vivaldi for productivity and i'm not sure what to think about it also being an emotional brand for "doing one's own thing frustratingly" ? (on [sidepanels](https://github.com/code-charity/youtube/discussions/2338#discussioncomment-9717479).  Sometimes i might  express the perspective of running an app over these years with special attention for the whole & details one never expected or wanted to care about, which can be mentally rewarding or painful. 

And i'm glad about your work as said!
Hope you are fine!

**Comment by ImprovedTube** [comment]
hi :) 🤗 you might want to read / catch up here https://github.com/code-charity/youtube/pull/2421 and other @mentiones
>Isn't it wonderful (mentally & and for the users), to have a project where at least 2 people have thought about 100s or 1000s of issues?

RE: License:  The first line indicates copyrights. 
> ©️ 2012-2024   ( no warranty / liablity )     Thank you! 

 (Then why quote halves of sentences?)  
 > For simplicity & intellectual growth: Unless stated otherwise, ... And free of copyrights to the original maintainers. (these intellectual contributions are granted to the original maintainers free-of-charge, non-exclusively, for publishing & modification. Contributors do have the right to be mentioned in credits)

( _In other words: External pull requests are assumed to be under a viral free license considering the rest of the world (as it is a common standard), but also with a normal (non-viral) permission (only to the original maintainers)(, so that and the original project can simply run as always / as the first 9 years when few pull requests were merged.)_ )
(you might also remember i offered you to commit directly)

- More interestingly, you might also read the draft for a new type of license acknowledging developers as shareholders (which they mentally are. Something that existing licenses are missing. Greetings @maniues)   
- While you were essential for the Project in 2024 💕.

**Comment by ImprovedTube** [comment]
(As said) i have a lot of understanding for your exhaustion(?) 

i was utterly amazed and so relieved you were working a lot these month!  And regret i was unable unexpectedly to work here in June.

**Comment by ImprovedTube** [comment]
And i don't know why to keep up "competitive misunderstandings"?  - to belittle ourselves and our project?   

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  

You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be?  i usually mean to apply the courtesy /professional-distance to comment rather positively and ignore confusing impulses  (among other since we represent a popular app in public. Feel free to use email to or any)

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a headline of some paragraph - when quoting badly isolated and we can speculatively assume Vivaldi misunderstood that - or i can just regret the lack of a public bug tracker.   I appreciated Vivaldi for productivity and i'm not sure what to think about it also being an emotional brand for "doing one's own thing frustratingly" ? (on [sidepanels](https://github.com/code-charity/youtube/discussions/2338#discussioncomment-9717479).  Sometimes i might  express the perspective of running an app over these years with special attention for the whole & details one never expected or wanted to care about, which can be mentally rewarding or painful. 

And i'm glad about your work as said!
Hope you are fine!

**Comment by ImprovedTube** [comment]
hi :) 🤗 you might want to read / catch up here https://github.com/code-charity/youtube/pull/2421 and other @mentiones
>Isn't it wonderful (mentally & and for the users), to have a project where at least 2 people have thought about 100s or 1000s of issues?

RE: License:  The first line indicates copyrights. 
> ©️ 2012-2024   ( no warranty / liablity )     Thank you! 

 (Then why quote halves of sentences?)  
 > For simplicity & intellectual growth: Unless stated otherwise, ... And free of copyrights to the original maintainers. (these intellectual contributions are granted to the original maintainers free-of-charge, non-exclusively, for publishing & modification. Contributors do have the right to be mentioned in credits)

( _In other words: External pull requests are assumed to be under a viral free license considering the rest of the world (as it is a common standard), but also with a normal (non-viral) permission (only to the original maintainers)(, so that and the original project can simply run as always / as the first 9 years when few pull requests were merged.)_ )

- More interestingly, you might also read the draft for a new type of license acknowledging developers as shareholders (which they mentally are. Something that existing licenses are missing. Greetings @maniues)   
- While you were essential for the Project in 2024 💕.

**Comment by ImprovedTube** [comment]
(As said) i have a lot of understanding for your exhaustion(?) 

i was utterly amazed and so relieved you were working a lot these month!  And regret i was unable unexpectedly to work here in June.

**Comment by ImprovedTube** [comment]
unsure  how and why "competitive misunderstandings" developed or not. (To belittle ourselves and our project? )

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  
You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be?  i usually mean to apply the courtesy /professional-distance to comment rather positively and ignore confusing impulses  (among other since we represent a popular app in public. Feel free to use email to or any)

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a headline of some paragraph - when quoting badly isolated and we can speculatively assume Vivaldi misunderstood that - or can just regret the lack of a public bug tracker.  I appreciated Vivaldi for productivity (and i'm not sure why it is such an emotional thing to some, about doing one's own thing despite of frustration?)

---

...

Glad about your work as said!
Hope you are fine!

**Comment by ImprovedTube** [comment]
unsure  how and why "competitive misunderstandings" developed or not. (To belittle ourselves and our project? )

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  
You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be?  i usually mean to apply the courtesy /professional-distance to comment rather positively and ignore confusing impulses  (among other since we represent a popular app in public. Feel free to use email to or any)

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a headline of some paragraph - when quoting badly isolated and we can speculatively assume Vivaldi misunderstood that - or can just regret the lack of a public bug tracker.  I appreciated Vivaldi for productivity (and i'm not sure why it is such an emotional thing to some, about doing one's own thing despite of frustration?)

---

...

---

Glad about your work!
Hope you are fine!

**Comment by ImprovedTube** [comment]
unsure  how and why to practice categorical /competitive misunderstandings. 
(To belittle ourselves and our project? )

https://github.com/code-charity/youtube/discussions/2287#discussioncomment-9717753 : 

> if anything https://github.com/code-charity/youtube/commit/912b34d6170d2ded3c605ee6ca7ae15a21700bdf broke it and NOW with this patch hyperlinks will have no color :)

...No.  
You already did so much! (Did that also make you any less-willing to "admit" tiny/every-day blunders?  /The more effort you pay, the more "silly" i must be?  i usually mean to apply the courtesy /professional-distance to comment rather positively and ignore confusing impulses  (among other since we represent a popular app in public. Feel free to use email to or any)

---

> a defector   

That was only about the tiny screenshot?  Or you didn't feel like a good team?

> **this is NOT vivaldi bug**

NO, chrome documentation did most-likely not refer to something only Vivaldi has & only 1 in 2000 browser users has
( i had told about the fun to run a project used by 0.0x% of youtube users & care for bugs unique to a browser used by 0.0x% browser users?  I am not sure how this was enough for an angry troll to come up, and even change your perception of truth?)  

(Yes, the chrome documentation has a headline of some paragraph - when quoting badly isolated and we can speculatively assume Vivaldi misunderstood that - or can just regret the lack of a public bug tracker.  I appreciated Vivaldi for productivity (and i'm not sure why it is such an emotional thing to some, about doing one's own thing despite of frustration?)

---

...

---

Glad about your work!
Hope you are fine!

**Pull request closed without merging**
